[package]
name = "cargo-creusot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { version = "1.0" }
toml = { version = "0.5.8", features = ["preserve_order"] }
env_logger = "*"
serde = { version = "1.0", features = ["derive"] }
directories = "5.0"
creusot-args = {path = "../creusot-args"}
which = "6.0"
anyhow = "1.0"
reqwest = { version = "0.11", features = ["blocking"] }
zip = "0.6"
hex = "0.4"
sha2 = "0.10"
