[package]
name = "creusot"
version = "0.1.0"
authors = ["Xavier Denis <xldenis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(NOT_A_PLATFORM)'.dependencies]
rustc_driver = { path = "/Users/xavier/Code/rust/rust/compiler/rustc_driver"}
rustc_hir = { path = "/Users/xavier/Code/rust/rust/compiler/rustc_hir"}
rustc_interface = { path = "/Users/xavier/Code/rust/rust/compiler/rustc_interface"}
rustc_mir = { path = "/Users/xavier/Code/rust/rust/compiler/rustc_mir"}
rustc_middle = { path = "/Users/xavier/Code/rust/rust/compiler/rustc_middle"}
rustc_index = { path = "/Users/xavier/Code/rust/rust/compiler/rustc_index"}
rustc_ast = { path = "/Users/xavier/Code/rust/rust/compiler/rustc_ast"}
rustc_ast_pretty = { path = "/Users/xavier/Code/rust/rust/compiler/rustc_ast_pretty"}
rustc_span = { path = "/Users/xavier/Code/rust/rust/compiler/rustc_span"}
