[workspace]
members = [
  "creusot",
  "creusot-contracts",
  "creusot-contracts-proc",
  "creusot-contracts-dummy",
  "creusot-metadata",
  "why3",
  "why3tests",
  "pearlite-syn",
  "creusot-rustc",
]

[profile.dev]
split-debuginfo = "unpacked"
