[package]
name = "creusot-contracts"
version = "0.1.0"
authors = ["Xavier Denis <xldenis@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "*"
uuid = { version = "*", features = ["v4"] }
syn = { version = "*", git = "https://github.com/xldenis/syn", branch = "spec-lang-2", features = ["full", "extra-traits", "visit"] }
# syn = { path = "../../syn-specs", features = ["full", "extra-traits"]}
proc-macro2 = "*"
[target.'cfg(NOT_A_PLATFORM)'.dependencies]
# proc_macro = { path = "/Users/xavier/Code/rust/rust/library/proc_macro" }
