[package]
name = "creusot"
version = "0.1.0"
authors = ["Xavier Denis <xldenis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
env_logger = "*"
log = "*"
# regex = "*"
# csv = "*"
serde = "1.0.117"
lazy_static = "*"
syn = { version = "*", git = "https://github.com/xldenis/syn", branch = "spec-lang-2", features = ["full"] }
quote = "*"
proc-macro2 = "*"
unescape = "*"
