[package]
name = "creusot"
version = "0.1.0"
authors = ["Xavier Denis <xldenis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
env_logger = "*"
log = "0.4"
# regex = "*"
# csv = "*"
serde = "1.0.117"
syn = { version = "*", git = "https://github.com/xldenis/syn", branch = "spec-lang-2", features = ["full", "extra-traits", "visit"] }
quote = "*"
proc-macro2 = "*"
unescape = "0.1"
sequence_trie = "0.3.6"
heck = "0.3"

[dev-dependencies]
glob = "*"
datatest= "0.6"
assert_cmd = "1.0"
mktemp = "0.4"
file_diff = "1.0"
