[package]
name = "pearlite-syn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

syn = { version = "*", features = ["full", "extra-traits"] }
proc-macro2 = "*"
quote = "*"

[features]

default = ["full"]
full = ["parsing", "printing"]
printing = []
parsing = []

[dev-dependencies]
insta = "1.0"
ref-cast = "1.0"
